backend:
  name: git-gateway
  repo: /ModdingCafe/MDCFBlog
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
# publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/media" # Media files will be stored in the repo under static/images/
public_folder: "/media" # The src attribute for uploaded media will begin with /images/

collections:
  - name: "posts"
    label: "Posts"
    label_singular: 'Post'
    folder: "content/posts"
    path: '{{slug}}/index'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Body
        name: body
        widget: markdown
      - label: Featured Image
        name: featured_image
        widget: string
      - label: Youtube ID
        name: youtube_id
        widget: string